import "./globals.css";
import Header from "./ui/root-layout/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className={`antialiased`}>{children}</main>
      </body>
    </html>
  );
}
